// src/redux/actionTypes.js
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';
