export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';

export const DELETE_STUDENT = 'DELETE_STUDENT';

export const UPDATE_STUDENT_STATUS = 'UPDATE_STUDENT_STATUS';
export const UPDATE_STUDENT_STATUS_START = 'UPDATE_STUDENT_STATUS_START';
export const UPDATE_STUDENT_STATUS_SUCCESS = 'UPDATE_STUDENT_STATUS_SUCCESS';
export const UPDATE_STUDENT_STATUS_FAILURE = 'UPDATE_STUDENT_STATUS_FAILURE';

