export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';
export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';
export const UPDATE_STUDENT_STATUS = 'UPDATE_STUDENT_STATUS';
export const UPDATE_STUDENT_STATUS_FAILURE = 'UPDATE_STUDENT_STATUS_FAILURE';


