// src/redux/classesActionTypes.js

export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_FAILURE = 'FETCH_CLASSES_FAILURE';

export const ADD_CLASS = 'ADD_CLASS';
export const ADD_CLASS_FAILURE = 'ADD_CLASS_FAILURE';

export const UPDATE_CLASS_START = 'UPDATE_CLASS_START';
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const UPDATE_CLASS_FAILURE = 'UPDATE_CLASS_FAILURE';

export const DELETE_CLASS = 'DELETE_CLASS';
