export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE';

export const UPDATE_COURSE_START = 'UPDATE_COURSE_START';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';

export const DELETE_COURSE = 'DELETE_COURSE';
