// src/redux/roomsActionTypes.js

export const FETCH_ROOMS_REQUEST = 'FETCH_ROOMS_REQUEST';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_FAILURE = 'FETCH_ROOMS_FAILURE';

export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_FAILURE = 'ADD_ROOM_FAILURE';

export const UPDATE_ROOM_START = 'UPDATE_ROOM_START';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_FAILURE = 'UPDATE_ROOM_FAILURE';

export const DELETE_ROOM = 'DELETE_ROOM';
