export const FETCH_SEMESTERS_REQUEST = 'FETCH_SEMESTERS_REQUEST';
export const FETCH_SEMESTERS_SUCCESS = 'FETCH_SEMESTERS_SUCCESS';
export const FETCH_SEMESTERS_FAILURE = 'FETCH_SEMESTERS_FAILURE';

export const ADD_SEMESTER = 'ADD_SEMESTER';
export const ADD_SEMESTER_FAILURE = 'ADD_SEMESTER_FAILURE';

export const UPDATE_SEMESTER = 'UPDATE_SEMESTER';
export const DELETE_SEMESTER = 'DELETE_SEMESTER';
