// === SUBJECT ACTION TYPES ===
export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const FETCH_SUBJECTS_REQUEST = 'FETCH_SUBJECTS_REQUEST';
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_FAILURE = 'FETCH_SUBJECTS_FAILURE';

export const ADD_SUBJECT = 'ADD_SUBJECT';
export const ADD_SUBJECT_FAILURE = 'ADD_SUBJECT_FAILURE';

export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const UPDATE_SUBJECT_START = 'UPDATE_SUBJECT_START';
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS';
export const UPDATE_SUBJECT_FAILURE = 'UPDATE_SUBJECT_FAILURE';

export const DELETE_SUBJECT = 'DELETE_SUBJECT';
