export const FETCH_TEACHERS = 'FETCH_TEACHERS';
export const FETCH_TEACHERS_REQUEST = 'FETCH_TEACHERS_REQUEST';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';
export const FETCH_TEACHERS_FAILURE = 'FETCH_TEACHERS_FAILURE';

export const ADD_TEACHER = 'ADD_TEACHER';
export const ADD_TEACHER_FAILURE = 'ADD_TEACHER_FAILURE';

export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const UPDATE_TEACHER_START = 'UPDATE_TEACHER_START';
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS';
export const UPDATE_TEACHER_FAILURE = 'UPDATE_TEACHER_FAILURE';

export const DELETE_TEACHER = 'DELETE_TEACHER';

export const UPDATE_TEACHER_STATUS = 'UPDATE_TEACHER_STATUS';
export const UPDATE_TEACHER_STATUS_START = 'UPDATE_TEACHER_STATUS_START';
export const UPDATE_TEACHER_STATUS_SUCCESS = 'UPDATE_TEACHER_STATUS_SUCCESS';
export const UPDATE_TEACHER_STATUS_FAILURE = 'UPDATE_TEACHER_STATUS_FAILURE';
