name: Create Pull Request

on:
  push:
    branches:
      - 'feature/*' # Trigger on push to feature branches

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Implement feature ${{ github.ref }}'
          body: |
            This PR implements the feature for ${{ github.ref }}. Closes #${{ github.ref }}
          base: main
          head: ${{ github.ref }}
